id = "rshtml"
name = "RsHtml"
version = "0.1.6"
schema_version = 1
authors = ["rshtml"]
description = "RsHtml Template Language Support"
repository = "https://github.com/rshtml/zed"

[grammars.rshtml]
repository = "https://github.com/GabrielSantarem/tree-sitter-rshtml"
rev = "c1310f9f671bf2fce775c790e28c34c45298968a"

[language_servers.rshtml-analyzer]
name = "RsHtml"
languages = ["RsHtml"]

[language_servers.rshtml-analyzer.language_ids]
"RsHtml" = "rshtml"

[language_servers.vscode-html-language-server]
name = "vscode-html-language-server"
languages = ["RsHtml", "HTML"]

[language_servers.vscode-html-language-server.language_ids]
"HTML" = "html"
"CSS" = "css"
"RsHtml" = "rshtml"
